name: Publish Website

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - site-build

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      env:
        CDN_API_ENDPOINT: ${{ secrets.CDN_API_ENDPOINT }}
        PUBLIC_CDN_API_ENDPOINT: ${{ secrets.CDN_API_ENDPOINT }}
        CDN_API_KEY: ${{ secrets.CDN_API_KEY }}

        PUBLIC_BASE_URL: ${{ secrets.BASE_URL }}
        BASE_URL: ${{ secrets.BASE_URL }}
      steps:
        - name: Get latest code
          uses: actions/checkout@v4
        
        - name: Setup bun
          uses: oven-sh/setup-bun@v2
        
        - run: bun install
        - run: bun run build
        - uses: actions/upload-artifact@v4
          with:
            name: dist
            path: ./dist
    upload:
      name: upload
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v4
        - uses: actions/download-artifact@v4
          with:
            name: dist
            path: ./dist
        - name: Sync files
          uses: airvzxf/ftp-deployment-action@latest
          with:
            server: ${{ secrets.FTP_HOST }}
            user: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            local_dir: ./dist/
            remote_dir: ${{ secrets.FTP_PATH }}

