name: Publish Website

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - site-build

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      env:
        CDN_API_ENDPOINT: ${{ secrets.CDN_API_ENDPOINT }}
        PUBLIC_CDN_API_ENDPOINT: ${{ secrets.CDN_API_ENDPOINT }}
        CDN_API_KEY: ${{ secrets.CDN_API_KEY }}

        PUBLIC_BASE_URL: ${{ secrets.BASE_URL }}
        BASE_URL: ${{ secrets.BASE_URL }}
      steps:
        - name: Get latest code
          uses: actions/checkout@v4
        
        - name: Setup bun
          uses: oven-sh/setup-bun@v2
        
        - run: bun install
        - run: bun run build

        - name: Sync files
          uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
          with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./dist/
            server-dir: ${{ secrets.FTP_PATH }}
            protocol: ftps

